### ISSUE TITLE
`min_required_nodes` doc is wrong

### ISSUE THREAD

**Issue by panicbit** [chridou/reool#75]
Looks like a copy & paste mistake
https://github.com/chridou/reool/blob/30371e50616e0f67054faf0ac627153101736161/src/config/mod.rs#L128-L130

Should probably look more like this:
https://github.com/chridou/reool/blob/30371e50616e0f67054faf0ac627153101736161/src/config/mod.rs#L55-L56

**Comment by chridou** [comment]
Uh, yes
